### ISSUE TITLE
Update PR Template to Align with MetaMask Extension and Mobile Standards

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/eslint-plugin-design-tokens#14]
### Description

To ensure consistency across MetaMask repositories and streamline the PR review process, we propose updating our current PR template to align with the standards used by the MetaMask [extension](https://github.com/MetaMask/metamask-extension/blob/9e21127c010782cf509b4c3ac97c7754426b07ce/.github/pull-request-template.md) and [mobile](https://github.com/MetaMask/metamask-mobile/blob/4be64ff313a682049177e4f4448c9b2188e1e214/.github/pull-request-template.md) repositories. This update will include the addition of specific sections and guidelines that encourage thorough descriptions, testing details, and adherence to MetaMask coding standards. By adopting this standardized approach, we aim to enhance the quality of our submissions and facilitate more efficient and effective PR reviews.

### Technical Details

- **Objective**: Revise the current PR template to incorporate the structure and content used in the MetaMask extension and mobile repositories.
- **Key Additions**:
  - A directive to initially submit PRs as drafts and mark them as "Ready for review" only after the template has been completely filled out.
  - Sections for describing the motivation and context of the changes, linking related issues, detailing manual testing steps, and providing before/after screenshots or recordings.
  - Checklists for both the PR author and reviewers to ensure all necessary steps are taken before merging.
- **Implementation Steps**:
  1. Review the PR template from the MetaMask extension repository for relevant sections and guidelines.
  2. Update our repository's PR template to reflect these standards, customizing as necessary to fit our specific project needs.
  3. Ensure the updated template emphasizes the importance of following MetaMask coding standards, documenting code, and applying appropriate labels.

### Acceptance Criteria

- The PR template in our repository is updated to closely align with the template used by the MetaMask extension and mobile repositories.
- The updated template includes clear directives for submitting PRs as drafts and criteria for marking them as ready for review.
- The template effectively guides contributors to provide comprehensive descriptions, testing details, and necessary documentation.
- Contributors can easily understand and follow the updated template, leading to higher quality PR submissions and more efficient review processes.

### Additional Notes

This initiative is part of our broader efforts to standardize development practices across MetaMask projects, fostering a cohesive and collaborative environment. By aligning our PR template with established MetaMask standards, we contribute to a more unified and efficient workflow across teams.

**Comment by JP2308** [comment]
More than happy to help with this one. See attached the slightly revised template,

**Comment by JP2308** [comment]
Happy to assist with this! 

I've replicated the PR template and included links to a new guidelines folder containing CODING_GUIDELINES and LABELING_GUIDELINES. 

Is this what you had in mind?
